# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []
# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
# on-focus-changed = ['move-mouse window-lazy-center']
on-focused-monitor-changed = ['move-mouse window-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 15
inner.vertical =   15
outer.left =       10
outer.bottom =     [{monitor.built-in = 10}, 100]
outer.top =        10
outer.right =      10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-ctrl-slash = 'layout tiles horizontal vertical'
alt-ctrl-quote = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-ctrl-z = 'focus left'
alt-ctrl-x = 'focus down'
alt-ctrl-o = 'focus up'
alt-ctrl-u = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-ctrl-z = 'move left'
alt-shift-ctrl-x = 'move down'
alt-shift-ctrl-o = 'move up'
alt-shift-ctrl-u = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-ctrl-8 = 'resize height +50'
alt-ctrl-7 = 'resize height -50'
alt-ctrl-9 = 'resize width +50'
alt-ctrl-6 = 'resize width -50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-ctrl-w = 'workspace 1'
alt-ctrl-l = 'workspace 2'
alt-ctrl-y = 'workspace 3'
alt-ctrl-p = 'workspace 4'
alt-ctrl-k = 'workspace 5'
# alt-ctrl-z = 'workspace 6'
# alt-ctrl-x = 'workspace 7'
# alt-ctrl-o = 'workspace 8'
# alt-ctrl-u = 'workspace 9'
# alt-ctrl-semicolon = 'workspace 10'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-ctrl-w = 'move-node-to-workspace --focus-follows-window 1'
alt-shift-ctrl-l = 'move-node-to-workspace --focus-follows-window 2'
alt-shift-ctrl-y = 'move-node-to-workspace --focus-follows-window 3'
alt-shift-ctrl-p = 'move-node-to-workspace --focus-follows-window 4'
alt-shift-ctrl-k = 'move-node-to-workspace --focus-follows-window 5'
# alt-shift-ctrl-z = 'move-node-to-workspace --focus-follows-window 6'
# alt-shift-ctrl-x = 'move-node-to-workspace --focus-follows-window 7'
# alt-shift-ctrl-o = 'move-node-to-workspace --focus-follows-window 8'
# alt-shift-ctrl-u = 'move-node-to-workspace --focus-follows-window 9'
# alt-shift-ctrl-semicolon = 'move-node-to-workspace --focus-follows-window 10'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-ctrl-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
# alt-ctrl-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-ctrl-space = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc =   ['reload-config', 'mode main']
r =     ['flatten-workspace-tree', 'mode main'] # reset layout
f =     ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
enter = ['balance-sizes', 'mode main']          # Balance window sizes
# backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-ctrl-z = ['join-with left', 'mode main']
alt-ctrl-x = ['join-with down', 'mode main']
alt-ctrl-o = ['join-with up', 'mode main']
alt-ctrl-u = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'secondary'
3 = 'main'
4 = 'secondary'
5 = 'main'
6 = 'main'
7 = 'main'
8 = 'main'
9 = 'main'
10 = 'main'
